# Codebase Improvement Configuration
# Customize the automated improvement cycles

[general]
# Interval between improvement cycles (in minutes)
cycle_interval = 60

# Maximum number of cycles per day
max_cycles_per_day = 24

# Enable/disable specific checks
enable_security_checks = true
enable_performance_analysis = true
enable_documentation_checks = true
enable_duplication_detection = true

[clippy]
# Clippy configuration
deny_warnings = true
apply_fixes_automatically = true

# Additional clippy lints to enable
extra_lints = [
    "clippy::all",
    "clippy::pedantic",
    "clippy::nursery",
    "clippy::cargo"
]

[formatting]
# Code formatting options
format_on_save = true
organize_imports = true

[testing]
# Test configuration
run_all_tests = true
generate_coverage_report = true
run_benchmarks = false
run_doc_tests = true

[security]
# Security check configuration
audit_dependencies = true
check_unsafe_code = true
analyze_panics = true

[performance]
# Performance analysis options
check_allocations = true
analyze_complexity = true
profile_hot_paths = false

[documentation]
# Documentation requirements
require_pub_docs = true
check_example_code = true
validate_links = false

[git]
# Git integration
auto_commit = true
create_branches = true
push_to_remote = false
branch_prefix = "auto-improvement"

[reporting]
# Report generation
generate_html_report = true
include_metrics = true
email_reports = false

[notifications]
# Notification settings
slack_webhook_url = ""
email_recipients = []
notify_on_errors = true
notify_on_completion = false
